# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
<<<<<<< HEAD
version: 2
=======
name: EESDevOps

on:
  push:
    branches: [master]

>>>>>>> 48ebb83fce3a000998721e570cf16d70a207d518
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: "Preparando o ambiente"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Instalando Dependências"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run:
          name: "Criar arquivo de ambiente e gerar app key"
          command: |
            mv .env.testing .env
            php artisan key:generate

      - run:
          name: "Criar banco de dados e subir migrações"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing

      - run:
          name: "Gerar Passport encryption keys"
          command: php artisan passport:install

      # run tests with phpunit
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit